/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Metadata } from '@grpc/grpc-js';
import { Observable } from 'rxjs';

export namespace Product {
  export interface ProductService {
    createProduct(
      data: CreateProductRequest,
      metadata?: Metadata,
    ): Observable<Empty>;
    getAllProducts(
      data: Empty,
      metadata?: Metadata,
    ): Observable<GetAllProductsResponse>;
  }
  // tslint:disable-next-line:no-empty-interface
  export interface Empty {}
  export interface CreateProductRequest {
    name?: string;
    description?: string;
    price?: number;
  }
  export interface Product {
    id?: string;
    name?: string;
    description?: string;
    price?: number;
  }
  export interface GetAllProductsResponse {
    products?: Product.Product[];
  }
}
